### PR TITLE
Use built-in json instead of simplejson

### PR DESCRIPTION
**Pull request by blag**
Update for Django 1.6

### CODE REVIEW

**Comment by RyanBalfanz** [comment]
Thanks, @blag. Did you happen to search the code for other uses of simplejson which should be replaced?

I'll merge this once any other uses are properly handled.

**Comment by blag** [comment]
Good catch. I removed the imports from `views.py` and `message.py` because they were not used.

These commits are untested because I'm not at my usual computer [editied through Github's web interface].

There is an `import json`, without a try/except wrapper, in `header.py`. I'm not sure what you want to do with that.

Let me know if you'd like me to do anything else.

**Comment by shangxiao** [comment]
This is absolutely necessary for use with 1.7 - any updates? :)

**Comment by RyanBalfanz** [comment]
I'm on vacation right now so won't be able to have a look for another day or two, unfortunately.—

**Pull request merged**
